# Default build parameters.  These may be overridden by local configuration
# settings in build.local.properties.
#

test.url.PGHOST=localhost
test.url.PGPORT=5432
secondaryServer1=localhost
secondaryPort1=5432
secondaryServer2=localhost
secondaryPort2=5432
database=yugabyte
username=yugabyte
password=yugabyte
privilegedUser=postgres
privilegedPassword=
sspiusername=testsspi
preparethreshold=5
sslpassword=sslpwd
